/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_aaa_bbb_MainActivity */

#ifndef _Included_com_aaa_bbb_MainActivity
#define _Included_com_aaa_bbb_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_aaa_bbb_MainActivity
 * Method:    nativeAdd
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_aaa_bbb_MainActivity_nativeAdd
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
